#!/usr/bin/env python3
"""Generate the BASIC token tables from docs/n88_keywords.txt.

Writes src/basic/tokens.inc (T_xxx equates for every keyword) and
src/basic/kwtable.inc (the keyword table used by the tokenizer and LIST):

  kw_index:  26 words, offset of the first entry for 'A'..'Z'
  entries:   db length, spelling without the first letter, token, flags
             (each letter group ends with db 0)

Flags (ours): KF_FUNC 01h = stored as FFh, token|80h; KF_LINE 10h = line
numbers follow; KF_DATA 20h = raw text to the end of the statement;
KF_ELSE 40h = ':' is stored before the token. Entries of one letter are
sorted longest first so the first match is the longest one.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'docs' / 'n88_keywords.txt'


def load():
    rows = []
    for line in SRC.read_text().splitlines():
        if not line or line.startswith('#'):
            continue
        word, tok, flags = line.split()
        rows.append((word.replace('_', ' '), int(tok, 16), int(flags, 16)))
    return rows


def name(word):
    n = word.replace(' ', '').replace('$', '_S').replace('?', 'QUEST')
    return {'+': 'PLUS', '-': 'MINUS', '*': 'MUL', '/': 'DIV', '^': 'POW',
            '\\': 'IDIV', '>': 'GT', '=': 'EQ', '<': 'LT'}.get(n, n)


def write(path, lines):
    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')


def main():
    rows = load()
    eq = ['; Generated by tools/gen_basic_tables.py from docs/n88_keywords.txt.',
          '; Statement tokens are stored as one byte; function tokens (< 80h) as',
          '; FFh followed by token|80h.', '']
    seen = set()
    for word, tok, flags in rows:
        n = name(word)
        if n in seen or word in ('L?', 'GO TO'):
            continue
        seen.add(n)
        prefix = 'F_' if tok < 0x80 else 'T_'
        eq.append(f'{prefix}{n:<12} equ {tok:03X}h')
    write(ROOT / 'src' / 'basic' / 'tokens.inc', eq)

    kw = ['; Generated by tools/gen_basic_tables.py from docs/n88_keywords.txt.',
          '; db length, spelling without the first letter, token, flags', '',
          'KF_FUNC         equ 01h', 'KF_LINE         equ 10h',
          'KF_DATA         equ 20h', 'KF_ELSE         equ 40h', '', 'kw_index:']
    groups = {chr(c): [] for c in range(ord('A'), ord('Z') + 1)}
    for word, tok, flags in rows:
        if word[0].isalpha() and word not in ('L?',):
            ours = 0x01 if tok < 0x80 else 0
            ours |= flags & 0x70
            groups[word[0]].append((word, tok, ours))
    for letter in groups:
        kw.append(f'    dw kw_{letter}')
    for letter, entries in groups.items():
        entries.sort(key=lambda e: -len(e[0]))
        kw.append(f'kw_{letter}:')
        for word, tok, flags in entries:
            rest = word[1:]
            chars = ', '.join(f"'{c}'" if c != "'" else '27h' for c in rest)
            body = f'{len(rest)}' + (f', {chars}' if rest else '')
            kw.append(f'    db {body}, {tok:03X}h, {flags:02X}h  ; {word}')
        kw.append('    db 0')
    write(ROOT / 'src' / 'basic' / 'kwtable.inc', kw)
    print(f'{len(seen)} tokens, {sum(len(g) for g in groups.values())} keywords')


if __name__ == '__main__':
    main()
