#!/usr/bin/env python3
"""Convert NP2kai's bios/keytable.res (BSD-3-Clause) into src/keytable.inc."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ESCAPES = {'\\\\': '\\', "\\'": "'", '\\"': '"'}

src = (ROOT / 'references/np2kai-bios/keytable.res').read_text(encoding='utf-8', errors='replace')

def literal(match):
    ch = match.group(0)[1:-1]
    return f'0x{ord(ESCAPES.get(ch, ch)):02x}'


# Replace character literals first so '{' and '}' cannot end a table early.
src = '\n'.join(re.sub(r"'(?:\\.|[^'])'", literal, line.split('//')[0]) + '//' +
                ('//'.join(line.split('//')[1:]) if '//' in line else '')
                for line in src.splitlines())
body = src[src.index('{') + 1:src.rindex('}')]
names, tables = [], []
for block in re.finditer(r'\{\s*//\s*(.*?)\n(.*?)\}', body, re.S):
    values = []
    for line in block.group(2).splitlines():
        line = line.split('//')[0]
        values += [int(tok, 16) for tok in re.findall(r'0x[0-9a-fA-F]+', line)]
    assert len(values) == 0x60, (block.group(1), len(values))
    names.append(block.group(1).strip())
    tables.append(values)
assert len(tables) == 8, len(tables)
out = ['; Keyboard code tables, 8 x 60h bytes (normal, shift, CAPS, shift+CAPS,',
       '; kana, shift+kana, GRPH, CTRL). Generated by tools/gen_keytable.py from',
       '; NP2kai bios/keytable.res. Copyright (c) 1999-2025 NP2 developer team,',
       '; BSD-3-Clause; see LICENSES/NP2kai.txt.']
for name, values in zip(names, tables):
    out.append(f'; {name}')
    for i in range(0, 0x60, 16):
        out.append('    db ' + ','.join(f'{v:03x}h' for v in values[i:i + 16]))
(ROOT / 'src/keytable.inc').write_text('\n'.join(out) + '\n')
print('wrote src/keytable.inc:', ', '.join(names))
